# Generated by Django 5.2.9 on 2026-06-17 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseRegistrationSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "telegram_group_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        verbose_name="Ссылка на Telegram-группу",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Настройка регистрации",
                "verbose_name_plural": "Настройки регистрации",
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Учебный год"
                    ),
                ),
                ("starts_on", models.DateField(verbose_name="Дата начала")),
                ("ends_on", models.DateField(verbose_name="Дата окончания")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активный"),
                ),
            ],
            options={
                "verbose_name": "Учебный год",
                "verbose_name_plural": "Учебные годы",
                "ordering": ["-starts_on"],
                "indexes": [
                    models.Index(fields=["is_active"], name="acad_year_active_idx"),
                    models.Index(
                        fields=["starts_on", "ends_on"], name="acad_year_dates_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="unique_acad_year_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Инструмент"
                    ),
                ),
            ],
            options={
                "verbose_name": "Инструмент",
                "verbose_name_plural": "Инструменты",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="unique_instrument_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="ФИО ученика"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="journal.instrument",
                        verbose_name="Инструмент",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ученик",
                "verbose_name_plural": "Ученики",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="CourseApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Отчество"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Мужской"), ("female", "Женский")],
                        max_length=10,
                        verbose_name="Пол",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Дата рождения")),
                (
                    "city_church",
                    models.CharField(max_length=255, verbose_name="Город / Церковь"),
                ),
                (
                    "instrument",
                    models.CharField(
                        max_length=255,
                        verbose_name="Музыкальный инструмент / партия в оркестре",
                    ),
                ),
                (
                    "music_education",
                    models.CharField(
                        choices=[
                            ("none", "Нет"),
                            ("self_taught", "Самоучка"),
                            ("basic", "Начальное"),
                            ("secondary", "Среднее"),
                            ("higher", "Высшее"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Музыкальное образование",
                    ),
                ),
                (
                    "student_phone",
                    models.CharField(max_length=32, verbose_name="Телефон ученика"),
                ),
                (
                    "parent_contacts",
                    models.TextField(blank=True, verbose_name="Телефон родителей"),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        verbose_name="Дополнительные вопросы или комментарии",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Подтверждена"),
                            ("rejected", "Отклонена"),
                        ],
                        default="confirmed",
                        help_text="Если заявка отклонена, ученик, пользователь и временные учетные данные удаляются из журнала.",
                        max_length=20,
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "generated_login",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Логин, созданный для ученика по этой заявке.",
                        max_length=150,
                        verbose_name="Созданный логин",
                    ),
                ),
                (
                    "journal_created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Дата создания ученика в журнале",
                    ),
                ),
                (
                    "journal_removed_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Дата удаления ученика из журнала",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_application",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь ученика",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_application",
                        to="journal.student",
                        verbose_name="Ученик в журнале",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на курсы",
                "verbose_name_plural": "Заявки на курсы",
                "ordering": ["-registration_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название группы"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_groups",
                        to="journal.academicyear",
                        verbose_name="Учебный год",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
                "ordering": ["academic_year__name", "name"],
            },
        ),
        migrations.AddField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="journal.studygroup",
                verbose_name="Группа",
            ),
        ),
        migrations.CreateModel(
            name="GroupSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок в журнале"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_subjects",
                        to="journal.studygroup",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет группы",
                "verbose_name_plural": "Предметы групп",
                "ordering": ["group__name", "sort_order", "subject__name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название предмета"
                    ),
                ),
                (
                    "final_grade_type",
                    models.CharField(
                        choices=[
                            ("numeric", "Пятибалльная (1-5, Н)"),
                            ("pass_fail", "Зачет/незачет"),
                        ],
                        default="numeric",
                        max_length=20,
                        verbose_name="Тип итоговой оценки",
                    ),
                ),
                (
                    "is_specialty",
                    models.BooleanField(
                        default=False, verbose_name="Предмет специальности"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "name"], name="subject_active_name_idx"
                    ),
                    models.Index(fields=["is_specialty"], name="subject_specialty_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="unique_subject_name"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="studygroup",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                related_name="study_groups",
                through="journal.GroupSubject",
                to="journal.subject",
                verbose_name="Предметы",
            ),
        ),
        migrations.AddField(
            model_name="groupsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_subjects",
                to="journal.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.CreateModel(
            name="SubjectResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_grade",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Экзамен"
                    ),
                ),
                (
                    "final_grade",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Итоговая оценка",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_results",
                        to="journal.academicyear",
                        verbose_name="Учебный год",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_results",
                        to="journal.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_results",
                        to="journal.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Итог по предмету",
                "verbose_name_plural": "Итоги по предметам",
                "ordering": [
                    "academic_year__name",
                    "student__full_name",
                    "subject__name",
                ],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="ФИО преподавателя"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преподаватель",
                "verbose_name_plural": "Преподаватели",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_specialty",
                    models.BooleanField(default=True, verbose_name="Специальность"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_subjects",
                        to="journal.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="individual_students",
                        to="journal.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="individual_subjects",
                        to="journal.teacher",
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Индивидуальный предмет ученика",
                "verbose_name_plural": "Индивидуальные предметы учеников",
                "ordering": ["student__full_name", "subject__name"],
            },
        ),
        migrations.AddField(
            model_name="groupsubject",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_subjects",
                to="journal.teacher",
                verbose_name="Преподаватель",
            ),
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата оценки")),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("Н", "Н"),
                        ],
                        max_length=10,
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если не указать, будет определён по дате оценки.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grades",
                        to="journal.academicyear",
                        verbose_name="Учебный год",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="journal.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grades",
                        to="journal.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grades",
                        to="journal.teacher",
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка",
                "verbose_name_plural": "Оценки",
                "ordering": ["-date", "student__full_name"],
            },
        ),
        migrations.CreateModel(
            name="TeacherSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_qualifications",
                        to="journal.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_qualifications",
                        to="journal.teacher",
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Квалификация преподавателя",
                "verbose_name_plural": "Квалификации преподавателей",
                "ordering": ["teacher__full_name", "subject__name"],
            },
        ),
        migrations.AddField(
            model_name="teacher",
            name="qualified_subjects",
            field=models.ManyToManyField(
                blank=True,
                related_name="qualified_teachers",
                through="journal.TeacherSubject",
                to="journal.subject",
                verbose_name="Предметы, которые может вести",
            ),
        ),
        migrations.CreateModel(
            name="TemporaryCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=150, verbose_name="Логин")),
                (
                    "temporary_password",
                    models.CharField(max_length=128, verbose_name="Временный пароль"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "student_phone",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Номер телефона ученика"
                    ),
                ),
                (
                    "course_application",
                    models.OneToOneField(
                        blank=True,
                        help_text="Заявка, по которой были выданы временные учетные данные.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_credential",
                        to="journal.courseapplication",
                        verbose_name="Заявка на курсы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Временные учетные данные",
                "verbose_name_plural": "Временные учетные данные",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="courseapplication",
            index=models.Index(
                fields=["status", "-registration_date"],
                name="course_app_status_reg_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="courseapplication",
            index=models.Index(fields=["student_phone"], name="course_app_phone_idx"),
        ),
        migrations.AddIndex(
            model_name="courseapplication",
            index=models.Index(fields=["generated_login"], name="course_app_login_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["group", "full_name"], name="student_group_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["instrument"], name="student_instrument_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["is_active"], name="student_active_idx"),
        ),
        migrations.AddIndex(
            model_name="studygroup",
            index=models.Index(
                fields=["academic_year", "name"], name="study_group_year_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studygroup",
            index=models.Index(fields=["is_active"], name="study_group_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="studygroup",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "name"), name="unique_group_name_per_year"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectresult",
            index=models.Index(
                fields=["academic_year", "subject"], name="result_year_subject_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectresult",
            index=models.Index(
                fields=["student", "academic_year"], name="result_student_year_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectresult",
            index=models.Index(
                fields=["subject", "student"], name="result_subject_student_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectresult",
            constraint=models.UniqueConstraint(
                fields=("student", "subject", "academic_year"),
                name="unique_result_student_subject_year",
            ),
        ),
        migrations.AddIndex(
            model_name="studentsubject",
            index=models.Index(
                fields=["student", "is_active"], name="student_subject_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentsubject",
            index=models.Index(
                fields=["teacher", "subject"], name="student_subject_teacher_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentsubject",
            index=models.Index(
                fields=["subject", "student"], name="subject_student_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentsubject",
            constraint=models.UniqueConstraint(
                fields=("student", "subject"), name="unique_student_ind_subject"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentsubject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_specialty", True)),
                fields=("student",),
                name="unique_active_specialty",
            ),
        ),
        migrations.AddIndex(
            model_name="groupsubject",
            index=models.Index(
                fields=["group", "sort_order"], name="group_subject_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupsubject",
            index=models.Index(
                fields=["teacher", "subject"], name="group_subject_teacher_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupsubject",
            index=models.Index(
                fields=["subject", "group"], name="group_subject_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupsubject",
            index=models.Index(fields=["is_active"], name="group_subject_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="groupsubject",
            constraint=models.UniqueConstraint(
                fields=("group", "subject"), name="unique_subject_per_group"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["student", "subject", "-date"], name="grade_student_subject_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["teacher", "-date"], name="grade_teacher_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["subject", "-date"], name="grade_subject_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["academic_year", "subject"], name="grade_year_subject_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(fields=["date"], name="grade_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("student", "subject", "date"),
                name="unique_grade_student_subject_date",
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubject",
            index=models.Index(
                fields=["teacher", "subject"], name="teacher_subject_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubject",
            index=models.Index(
                fields=["subject", "teacher"], name="subject_teacher_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teachersubject",
            constraint=models.UniqueConstraint(
                fields=("teacher", "subject"), name="unique_teacher_subject_qual"
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(fields=["full_name"], name="teacher_full_name_idx"),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(fields=["is_active"], name="teacher_active_idx"),
        ),
        migrations.AddIndex(
            model_name="temporarycredential",
            index=models.Index(fields=["login"], name="temp_cred_login_idx"),
        ),
        migrations.AddIndex(
            model_name="temporarycredential",
            index=models.Index(fields=["student_phone"], name="temp_cred_phone_idx"),
        ),
        migrations.AddIndex(
            model_name="temporarycredential",
            index=models.Index(fields=["-created_at"], name="temp_cred_created_idx"),
        ),
    ]
