# Generated by Django 5.2.7 on 2026-04-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'date'), name='unique_student_subject_grade_per_day'),
        ),
    ]
