# Generated by Django 6.0.2 on 2026-07-20 10:11

from django.conf import settings
from django.db import migrations, models


def copy_course_application_data_to_students(apps, schema_editor):
    CourseApplication = apps.get_model('journal', 'CourseApplication')
    Student = apps.get_model('journal', 'Student')

    for application in CourseApplication.objects.exclude(student_id__isnull=True).iterator():
        Student.objects.filter(pk=application.student_id).update(
            gender=application.gender,
            birth_date=application.birth_date,
            city_church=application.city_church,
            music_education=application.music_education,
            student_phone=application.student_phone,
            parent_contacts=application.parent_contacts,
            comments=application.comments,
        )


def clear_copied_course_application_data(apps, schema_editor):
    Student = apps.get_model('journal', 'Student')
    Student.objects.update(
        gender='',
        birth_date=None,
        city_church='',
        music_education='',
        student_phone='',
        parent_contacts='',
        comments='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='student',
            name='city_church',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город / Церковь'),
        ),
        migrations.AddField(
            model_name='student',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Дополнительные вопросы или комментарии'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='student',
            name='music_education',
            field=models.CharField(blank=True, choices=[('none', 'Нет'), ('self_taught', 'Самоучка'), ('basic', 'Начальное'), ('secondary', 'Среднее'), ('higher', 'Высшее')], max_length=20, verbose_name='Музыкальное образование'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_contacts',
            field=models.TextField(blank=True, verbose_name='Телефон родителей'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон ученика'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.RunPython(
            copy_course_application_data_to_students,
            clear_copied_course_application_data,
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_phone'], name='student_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['birth_date'], name='student_birth_date_idx'),
        ),
    ]
