# Generated by Django 6.0.2 on 2026-07-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_student_birth_date_student_city_church_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRecoveryContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя администратора')),
                ('phone', models.CharField(max_length=32, verbose_name='Номер телефона')),
                ('messengers', models.CharField(help_text='Укажите один или несколько мессенджеров, например: Telegram, WhatsApp.', max_length=255, verbose_name='Мессенджеры')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать пользователям')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок показа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Контакт администратора',
                'verbose_name_plural': 'Настройки восстановления пароля',
                'db_table': 'journal_password_recovery_settings',
                'ordering': ['display_order', 'name', 'pk'],
            },
        ),
    ]
