# Generated by Django 6.0.2 on 2026-07-22 11:21

import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_passwordrecoverycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistrationsettings',
            name='course_ends_on',
            field=models.DateField(default=journal.models.default_course_ends_on, verbose_name='Дата окончания курсов'),
        ),
        migrations.AddField(
            model_name='courseregistrationsettings',
            name='course_starts_on',
            field=models.DateField(default=journal.models.default_course_starts_on, verbose_name='Дата начала курсов'),
        ),
        migrations.AddField(
            model_name='courseregistrationsettings',
            name='minimum_registration_age',
            field=models.PositiveSmallIntegerField(default=14, help_text='Возраст считается на дату начала курсов.', verbose_name='Минимальный возраст для регистрации'),
        ),
    ]
