# Generated by Django 6.0.2 on 2026-07-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_courseregistrationsettings_course_ends_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='is_specialty',
            field=models.BooleanField(default=False, verbose_name='Индивидуальный предмет'),
        ),
    ]
