# Generated by Django 6.0.2 on 2026-05-23 21:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_grade', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Экзамен')),
                ('final_grade', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Итоговая оценка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='journal.student', verbose_name='Ученик')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='journal.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Итог по предмету',
                'verbose_name_plural': 'Итоги по предметам',
                'ordering': ['student__full_name', 'subject__name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'subject'), name='unique_student_subject_result')],
            },
        ),
    ]
