# Generated by Django 6.0.2 on 2026-05-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_subjectresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.CharField(max_length=1, verbose_name='Оценка'),
        ),
    ]
