# Generated by Django 6.0.2 on 2026-05-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_grade_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='final_grade_type',
            field=models.CharField(choices=[('numeric', 'Пятибалльная (1-5, Н)'), ('pass_fail', 'Зачет/незачет (зачет, незачет, Н)')], default='numeric', max_length=20, verbose_name='Тип итоговой оценки'),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='exam_grade',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Экзамен'),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='final_grade',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Итоговая оценка'),
        ),
    ]
