# Generated by Django 6.0.2 on 2026-07-22 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_temporary_credentials_to_users(apps, schema_editor):
    TemporaryCredential = apps.get_model('journal', 'TemporaryCredential')
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(user_app_label, user_model_name)

    user_ids_by_username = dict(User.objects.values_list('username', 'id'))
    credentials = []
    for credential in TemporaryCredential.objects.filter(user__isnull=True).only('id', 'login'):
        user_id = user_ids_by_username.get(credential.login)
        if user_id is None:
            continue
        credential.user_id = user_id
        credentials.append(credential)

    if credentials:
        TemporaryCredential.objects.bulk_update(credentials, ['user'])


def unlink_temporary_credentials_from_users(apps, schema_editor):
    TemporaryCredential = apps.get_model('journal', 'TemporaryCredential')
    TemporaryCredential.objects.update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_student_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarycredential',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пользователь, которому выданы временные учетные данные.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_credentials', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.RunPython(
            link_temporary_credentials_to_users,
            unlink_temporary_credentials_from_users,
        ),
        migrations.AlterField(
            model_name='temporarycredential',
            name='student_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AddIndex(
            model_name='temporarycredential',
            index=models.Index(fields=['user'], name='temp_cred_user_idx'),
        ),
    ]
