# Generated by Django 6.0.2 on 2026-07-22 23:02

from django.conf import settings
from django.db import migrations, models


def normalize_records_before_constraints(apps, schema_editor):
    AcademicYear = apps.get_model('journal', 'AcademicYear')
    TemporaryCredential = apps.get_model('journal', 'TemporaryCredential')

    latest_year = AcademicYear.objects.order_by('-starts_on', '-ends_on', '-id').first()
    if latest_year is not None:
        AcademicYear.objects.filter(pk=latest_year.pk).update(is_active=True)
        AcademicYear.objects.exclude(pk=latest_year.pk).update(is_active=False)

    seen_user_ids = set()
    duplicate_credential_ids = []
    for credential in (
        TemporaryCredential.objects
        .exclude(user_id__isnull=True)
        .order_by('user_id', 'id')
        .only('id', 'user_id')
    ):
        if credential.user_id in seen_user_ids:
            duplicate_credential_ids.append(credential.pk)
        else:
            seen_user_ids.add(credential.user_id)

    if duplicate_credential_ids:
        TemporaryCredential.objects.filter(pk__in=duplicate_credential_ids).delete()

    seen_logins = set()
    duplicate_credential_ids = []
    for credential in TemporaryCredential.objects.order_by('login', 'id').only('id', 'login'):
        if credential.login in seen_logins:
            duplicate_credential_ids.append(credential.pk)
        else:
            seen_logins.add(credential.login)

    if duplicate_credential_ids:
        TemporaryCredential.objects.filter(pk__in=duplicate_credential_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_temporarycredential_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistrationRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True, verbose_name='Ключ ограничения')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Количество попыток')),
                ('window_started_at', models.DateTimeField(verbose_name='Начало окна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Ограничение регистрации',
                'verbose_name_plural': 'Ограничения регистрации',
            },
        ),
        migrations.RunPython(
            normalize_records_before_constraints,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='temporarycredential',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_temp_credential_user'),
        ),
        migrations.AddConstraint(
            model_name='temporarycredential',
            constraint=models.UniqueConstraint(fields=('login',), name='unique_temp_credential_login'),
        ),
        migrations.AddIndex(
            model_name='courseregistrationratelimit',
            index=models.Index(fields=['cache_key'], name='course_reg_rate_key_idx'),
        ),
        migrations.AddIndex(
            model_name='courseregistrationratelimit',
            index=models.Index(fields=['window_started_at'], name='course_reg_rate_window_idx'),
        ),
    ]
