# Generated by Django 6.0.2 on 2026-06-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_alter_subject_final_grade_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistrationSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('telegram_group_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на Telegram-группу')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Настройка регистрации',
                'verbose_name_plural': 'Настройки регистрации',
            },
        ),
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('city_church', models.CharField(max_length=255, verbose_name='Город / Церковь')),
                ('instrument', models.CharField(max_length=255, verbose_name='Музыкальный инструмент / партия в оркестре')),
                ('music_education', models.CharField(choices=[('none', 'Нет'), ('self_taught', 'Самоучка'), ('basic', 'Начальное'), ('secondary', 'Среднее'), ('higher', 'Высшее')], default='none', max_length=20, verbose_name='Музыкальное образование')),
                ('student_phone', models.CharField(max_length=32, verbose_name='Телефон ученика')),
                ('parent_contacts', models.TextField(blank=True, verbose_name='Телефон родителей')),
                ('comments', models.TextField(blank=True, verbose_name='Дополнительные вопросы или комментарии')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('rejected', 'Отклонена'), ('enrolled', 'Зачислен')], default='new', max_length=20, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявка на курсы',
                'verbose_name_plural': 'Заявки на курсы',
                'ordering': ['-registration_date', '-id'],
                'indexes': [models.Index(fields=['status', '-registration_date'], name='course_app_status_reg_idx')],
            },
        ),
    ]
