# Generated by Django 5.2.7 on 2026-06-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_create_course_registration_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, verbose_name='Логин')),
                ('temporary_password', models.CharField(max_length=128, verbose_name='Временный пароль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
            ],
            options={
                'verbose_name': 'Временные учетные данные',
                'verbose_name_plural': 'Временные учетные данные',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
