# Generated by Django 5.2.7 on 2026-06-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_temporarycredential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarycredential',
            name='is_used',
        ),
    ]
