# Generated by Django 5.2.7 on 2026-06-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_remove_temporarycredential_is_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryStudentCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, verbose_name='Логин')),
                ('temporary_password', models.CharField(max_length=128, verbose_name='Временный пароль')),
                ('phone_number', models.CharField(max_length=32, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Временные учетные данные ученика',
                'verbose_name_plural': 'Временные учетные данные учеников',
                'ordering': ['-id'],
            },
        ),
    ]
