# Generated by Django 5.2.16 on 2026-07-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_clarify_course_application_status_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistrationsettings',
            name='minimum_registration_age',
            field=models.PositiveSmallIntegerField(default=14, help_text='Возраст считается на дату начала активного учебного года.', verbose_name='Минимальный возраст для регистрации'),
        ),
    ]
