# Generated by Django 5.2.9 on 2026-07-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0020_registration_age_year_and_music_education_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseapplication",
            name="instrument",
            field=models.CharField(
                help_text="Отображаемое значение, синхронизированное со структурированными полями.",
                max_length=255,
                verbose_name="Музыкальный инструмент / партия в оркестре",
            ),
        ),
    ]
