# Generated by Django 6.0.2 on 2026-07-30 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0025_orchestra_part_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentgroup',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_groups', to='journal.academicyear', verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='assessmentgroup',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_groups', to='journal.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='assessmentitem',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_items', to='journal.academicyear', verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='assessmentitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='journal.assessmentgroup', verbose_name='Группа произведений'),
        ),
        migrations.AlterField(
            model_name='assessmentitem',
            name='responsible_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_assessment_items', to='journal.teacher', verbose_name='Ответственный преподаватель-дирижёр'),
        ),
        migrations.AlterField(
            model_name='assessmentitem',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_items', to='journal.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results_given', to='journal.teacher', verbose_name='Преподаватель, выставивший результат'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='journal.studentenrollment', verbose_name='Зачисление ученика'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='journal.assessmentitem', verbose_name='Произведение / элемент'),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='academic_year',
            field=models.ForeignKey(blank=True, editable=False, help_text='Учебный год, в рамках которого подана заявка.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_applications', to='journal.academicyear', verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='instrument_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_applications', to='journal.instrument', verbose_name='Инструмент из справочника'),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='orchestra_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_applications', to='journal.orchestrapart', verbose_name='Партия в оркестре'),
        ),
        migrations.AlterField(
            model_name='finalgraderule',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grade_rules', to='journal.academicyear', verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='finalgraderule',
            name='assessment_group',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым для общего правила предмета.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_grade_rules', to='journal.assessmentgroup', verbose_name='Группа произведений'),
        ),
        migrations.AlterField(
            model_name='finalgraderule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grade_rules', to='journal.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Если не указать, будет определён по дате оценки.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='journal.academicyear', verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='enrollment',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='journal.studentenrollment', verbose_name='Зачисление ученика'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='journal.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='journal.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='groupsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_subjects', to='journal.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='groupsubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_subjects', to='journal.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='orchestrapart',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchestra_parts', to='journal.instrument', verbose_name='Инструмент'),
        ),
        migrations.AlterField(
            model_name='student',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='journal.instrument', verbose_name='Инструмент из справочника'),
        ),
        migrations.AlterField(
            model_name='student',
            name='orchestra_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='journal.orchestrapart', verbose_name='Партия в оркестре'),
        ),
        migrations.AlterField(
            model_name='studentassessmentgroup',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assessment_group_assignments', to='journal.academicyear', verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='studentassessmentgroup',
            name='assessment_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='journal.assessmentgroup', verbose_name='Группа произведений'),
        ),
        migrations.AlterField(
            model_name='studentassessmentgroup',
            name='enrollment',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_group_assignments', to='journal.studentenrollment', verbose_name='Зачисление ученика'),
        ),
        migrations.AlterField(
            model_name='studentassessmentgroup',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_group_assignments', to='journal.student', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='journal.academicyear', verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='journal.student', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='academic_year',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_subjects', to='journal.academicyear', verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_students', to='journal.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_subjects', to='journal.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_groups', to='journal.academicyear', verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='journal.academicyear', verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='enrollment',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='journal.studentenrollment', verbose_name='Зачисление ученика'),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='journal.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='teacherenrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_enrollments', to='journal.academicyear', verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='teacherenrollment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_year_memberships', to='journal.teacher', verbose_name='Преподаватель'),
        ),
    ]
