# Generated by Django 6.0.2 on 2026-07-30 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_user_year_memberships(apps, schema_editor):
    AcademicYear = apps.get_model('journal', 'AcademicYear')
    StudentEnrollment = apps.get_model('journal', 'StudentEnrollment')
    TeacherEnrollment = apps.get_model('journal', 'TeacherEnrollment')
    UserAcademicYearMembership = apps.get_model('journal', 'UserAcademicYearMembership')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    memberships = {}
    for user_id, academic_year_id, is_active in StudentEnrollment.objects.exclude(
        student__user_id__isnull=True,
    ).values_list('student__user_id', 'academic_year_id', 'is_active'):
        key = (user_id, academic_year_id)
        memberships[key] = memberships.get(key, False) or is_active

    for user_id, academic_year_id, is_active in TeacherEnrollment.objects.exclude(
        teacher__user_id__isnull=True,
    ).values_list('teacher__user_id', 'academic_year_id', 'is_active'):
        key = (user_id, academic_year_id)
        memberships[key] = memberships.get(key, False) or is_active

    active_year_id = AcademicYear.objects.filter(is_active=True).values_list('pk', flat=True).first()
    if active_year_id:
        for user_id in User.objects.filter(is_staff=True, is_active=True).values_list('pk', flat=True):
            memberships[(user_id, active_year_id)] = True

    UserAcademicYearMembership.objects.bulk_create([
        UserAcademicYearMembership(
            user_id=user_id,
            academic_year_id=academic_year_id,
            is_active=is_active,
        )
        for (user_id, academic_year_id), is_active in memberships.items()
    ])


def clear_user_year_memberships(apps, schema_editor):
    apps.get_model('journal', 'UserAcademicYearMembership').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0026_alter_assessmentgroup_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAcademicYearMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен в учебном году')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='journal.academicyear', verbose_name='Учебный год')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_year_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участие пользователя в учебном году',
                'verbose_name_plural': 'Участие пользователей в учебных годах',
                'ordering': ['-academic_year__starts_on', 'user__username'],
                'indexes': [models.Index(fields=['academic_year', 'user'], name='user_year_membership_idx'), models.Index(fields=['user', 'is_active'], name='user_year_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'academic_year'), name='unique_user_academic_year_membership')],
            },
        ),
        migrations.RunPython(
            populate_user_year_memberships,
            clear_user_year_memberships,
        ),
    ]
