# Generated by Django 5.2.9 on 2026-08-01 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0038_canonical_journal_assignments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsubject",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_subjects",
                to="journal.academicyear",
                verbose_name="Учебный год",
            ),
        ),
    ]
